package Main;

import ControllerLogin.ControllerLogin;
import ServiceVericCreden.ServiceVericCreden;
import UtilVerif.UtilVericCpf;
import UtilVerif.UtilVericSenha;

public class LoginView extends javax.swing.JFrame {

    UtilVericCpf vericCpf = new UtilVericCpf();
    UtilVericSenha vericSenha = new UtilVericSenha();
    ServiceVericCreden serviceVericCreden = new ServiceVericCreden();
    ControllerLogin controllerLogin = new ControllerLogin();

    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextCpfLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ButtSairLogin = new javax.swing.JButton();
        ButtLogin = new javax.swing.JButton();
        TextSenhaLogin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("BANCO NEB");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("QUE BOM TE VER DE NOVO!");

        TextCpfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCpfLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("SENHA");

        ButtSairLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtSairLogin.setText("SAIR");
        ButtSairLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtSairLoginActionPerformed(evt);
            }
        });

        ButtLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ButtLogin.setText("ENTRAR");
        ButtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(349, 349, 349))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(341, 341, 341))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtLogin)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtSairLogin)
                                .addGap(13, 13, 13)))
                        .addGap(319, 319, 319))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TextCpfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(TextSenhaLogin))
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(252, 252, 252))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextCpfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(ButtLogin)
                .addGap(66, 66, 66)
                .addComponent(ButtSairLogin)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCpfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCpfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCpfLoginActionPerformed

    private void ButtSairLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtSairLoginActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtSairLoginActionPerformed

    private void ButtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtLoginActionPerformed
        String cpf = TextCpfLogin.getText();
        String senhaEntr = TextSenhaLogin.getText();

        // Verificar CPF
        boolean vericQuantCpf = vericCpf.vericQuant(cpf);
        if (!vericQuantCpf) {
            javax.swing.JOptionPane.showMessageDialog(this, "CPF inválido! O CPF deve ter 11 dígitos.");
            return;
        }

        // Verificar Senha
        boolean vericQuantSenha = vericSenha.vericQuant(senhaEntr);
        if (!vericQuantSenha) {
            javax.swing.JOptionPane.showMessageDialog(this, "Senha inválida! A senha deve ter 8 dígitos.");
            return;
        }

        // Chama o serviço para verificar se o login é válido
        Integer idClienteControl = controllerLogin.loginEntrada(cpf, senhaEntr);

        if (idClienteControl != null) {
            ClieIniView civ = new ClieIniView();
            civ.setIdCliente(idClienteControl);
            this.dispose();
            civ.setVisible(true);

        } else {
            
            javax.swing.JOptionPane.showMessageDialog(this, "CPF ou senha incorretos. Tente novamente.");
        }
    }//GEN-LAST:event_ButtLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new LoginView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtLogin;
    private javax.swing.JButton ButtSairLogin;
    private javax.swing.JTextField TextCpfLogin;
    private javax.swing.JPasswordField TextSenhaLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
